;; ASCII ;;
; W: wall, D: door, k: key, g: gem, G: goal-gem, s: start, .: empty
; .W......W  (y=1)
; .WDWWWWWW  (y=2)  door2 at x=3? no door at (3,2)... wait
; .W.WWDWW.  (y=3)  door1=(3,3), door4=(6,4)... let me not include ascii
(define (problem doors-keys-gems-8)
  (:domain doors-keys-gems)
  (:objects door1 door2 door3 door4 - door
            key1 key2 key3 - key
            gem1 gem2 gem3 - gem)
  (:init (locked door1)
         (locked door2)
         (locked door3)
         (locked door4)
         (= (walls)
            (transpose (bit-mat
               (bit-vec 0 1 0 0 0 0 0 1)
               (bit-vec 0 1 0 1 1 1 1 1)
               (bit-vec 0 1 0 1 1 0 1 0)
               (bit-vec 0 1 0 1 1 0 1 0)
               (bit-vec 0 1 0 0 0 0 0 0)
               (bit-vec 0 1 0 1 1 0 0 0)
               (bit-vec 0 1 0 1 1 1 1 1)
               (bit-vec 0 0 0 0 0 0 0 0))))
         (= (xloc door1) 3)
         (= (yloc door1) 3)
         (= (xloc door2) 5)
         (= (yloc door2) 5)
         (= (xloc door3) 8)
         (= (yloc door3) 4)
         (= (xloc door4) 6)
         (= (yloc door4) 4)
         (= (xloc key1) 1)
         (= (yloc key1) 8)
         (= (xloc key2) 3)
         (= (yloc key2) 1)
         (= (xloc key3) 7)
         (= (yloc key3) 1)
         (= (xloc gem1) 1)
         (= (yloc gem1) 1)
         (= (xloc gem2) 6)
         (= (yloc gem2) 3)
         (= (xloc gem3) 8)
         (= (yloc gem3) 3)
         (= (xpos) 8)
         (= (ypos) 8))
  (:goal (has gem3))
)
